### ISSUE TITLE
Create budget for the EME 150A and EME 185 supplies

### ISSUE THREAD

**Issue by moorepants** [moorepants/eng-edu#15]
@viviantran27 The chair asked me to come up with a budget for everything we are buying for the things you have been working on. We need to do this, or otherwise the funds might not be there. There some parts to this:
1. Cost of design studio stuff that isn't directly related to one specific course (like furniture)
2. Cost of materials for piloting the activities in each course (costs of first implementation)
3. Ongoing costs for the courses (rebuying materials each time)
4. Initial costs of the 3d printers (sorta belongs in 1 but I have prior approval for purchasing these).
5. Ongoing costs of the 3d printers.

Felicia sent me some specific account #s that are different than before that these 1, 2, and 3 would be tied too. And the costs will not be approved for future unless I give them some idea about this. We can keep budgets for 4 and 5 in the 3d printer proposal.

This needs to get sorted out soon, especially 1 and 2.

**Comment by viviantran27** [comment]
I'll get it done soon. 

Do I just put the purchases already made on a spreadsheet or are you looking for something more for 1? The only ongoing costs are for supplying the kiosk with materials (and 3D printer related things), so should this go on this, too? I'm assuming future purchases like the odd-ball materials, e.g.Play Doh, should be because it probably won't be covered by the department, but should office supply costs that are already covered by the department go on this?

Destiny has the list of materials we came up with yesterday for EME150A, so I'll ask her about this. Is there anything for EME185 or any other classes that 2 and 3 should include?

**Comment by viviantran27** [comment]
[Here's the link to the spreadsheet for the EME 150A budget. 
](https://docs.google.com/a/ucdavis.edu/spreadsheets/d/1Rsv450DG7p8__VS0FknPz5jRYoWoCJCArA1Y4IPvZIk/edit?usp=sharing)

**Comment by viviantran27** [comment]
[This is the link to the Design Studio budget spreadsheet.](https://docs.google.com/a/ucdavis.edu/spreadsheets/d/1E_t1qMHhNycI2o5gHYRxVa0QvxTsUSG7lwRktbH8d3Q/edit?usp=sharing)

This is still in process, but past purchases are on there.
